### ISSUE TITLE
Self compiling Client for unsupported OS ?

### ISSUE THREAD

**Issue by Vaarlion** [DefGuard/client#360]
Hello

We are currently evaluating Defguard as a replacement for our wireguard setup, with the Google OICD and Automatic config update being a huge deal for us.

Sadly, the client, required for 2FA and Automatic config update, is prety much incompatible with everyone here :(
Our staff either run:
- Fedora: the absence of rpm, flatpak or appimage (that you still have a broken download link on your site btw) mean we have to use the binary exec, and this one doesn't work as we get an error saying the background job didn't start. (Tray icon do show up)
- Ubuntu 20: The DEB file require a more recent version of GlibC than provided by Ubuntu, and you can't update that without breaking everything
- Ubuntu 24: Some people have updated from 20 to 24, skipping 22 ... bummer. There is a workaround for them, but it's a minority.

From my testing using VM, only Ubuntu 22 and Windows seem supported. (No mac on hand) And this just won't do for us.

Outside of Ubuntu 24, that we have a work around for, Is there a way for us to compile Working version of the app for Ubuntu 20 and Fedora ? Or is the underlying code truly incompatible ?

Thank's for your input on this.

**Comment by teon** [comment]
@Vaarlion yes - we have more and more requests about this, we're take it on current sprint backlog. Thanks.

**Comment by Vaarlion** [comment]
Ok thank's !

The product is really promising, i'm hopping to be able to push for the enterprise subscription as soon as we have migrated our Infra team to it and proven it's reliability :D

I really don't want to onboard all our user manually XD

**Comment by teon** [comment]
@Vaarlion we've implemented RPM packages

**Comment by Vaarlion** [comment]
I've seen (and liked) the commit to the build pipeline and i'm waiting for a build of the client to get out :)
Thanks.

I still don't really know how to build it myself tho, since it look like your pipeline run on your personal runner.
You making an RPM version will help a lot, don't get this wrong. But i feel like a section in the wiki about how to build the client manually would be a great addition. That way maybe i could compile a version compatible with our Ubuntu 20 user, or other odd distro if we need to.

On my side, i got the green light to get the paid licensees for our defguard, the goal is to migrate before the end of the years, only a couple of routing issue to finish solving.

**Comment by teon** [comment]
@Vaarlion that's a good point - we will add info how to build the client.

**Comment by Vaarlion** [comment]
We got the product key and have started migrating our user
When trying the pre released 1.1.0 rpm, we are missing a couple of file compared to the deb file

- usr/lib doesn't have a defguard-client with the icon data
- the usr/share folder, including the application .desktop and the icons are missing.
- a .build-id is left from the build process in /usr/lib in the .rpm file

I would love to be able to test build this myself and see if i can fix those, please keep me updated about the build documentation release :D

**Comment by Vaarlion** [comment]
>This is fixed in https://github.com/DefGuard/client/pull/366.

Nice ! i'll wait for a new build but i'm already using the previous one with the extra file from the .deb pkg and it work great for me :)

> As far as I know, .build_id should be in RPM, no? https://unix.stackexchange.com/questions/411727/what-is-the-purpose-of-usr-lib-build-id-dir

You are probably right, i never built RPM and assumed based on the file name, format and path that this looked like a relica and not on purpose ^^ Sorry about this !

Are snap version with the needed dependency to be expected for ubuntu 22 or do i provide a script to my user do add the old repo and install the requirement like you indicate in your FAQ ?

**Comment by teon** [comment]
@Vaarlion new beta version of RPM: https://github.com/DefGuard/client/releases/tag/v1.1.1

**Comment by Vaarlion** [comment]
I'm currently testing it and i've ask for a coworker to do the same :) Thank you

Any new's about the self complication documentation for our user under ubuntu 20 ?

**Comment by kchudy** [comment]
Added a separate issue for updating contribution docs https://github.com/DefGuard/docs/issues/61. Closing this one.
